// flow-typed signature: d439a8aa6e84b76353abd325936457ec
// flow-typed version: <<STUB>>/@types/node_v^7.0.11/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
