// flow-typed signature: e4915efb61f2fca5a6a10d0d4d16e30c
// flow-typed version: <<STUB>>/daggy_v0.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'daggy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'daggy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'daggy/daggy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'daggy/daggy.js' {
  declare module.exports: $Exports<'daggy/daggy'>;
}
